add missing line "import com.calendarevents.CalendarEventsPackage;" to README file
To prevent error:

```
:app:compileDebugJavaWithJavac
/Users/tonatiuh/projects/peppaa/android/app/src/main/java/com/peppaa/MainApplication.java:33: error: cannot find symbol
            new CalendarEventsPackage()
                ^
  symbol: class CalendarEventsPackage
1 error
Incremental compilation of 1 classes completed in 0.142 secs.
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```